name: feishu_push_msg

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test_msg_type_post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send feishu message with custom action
        uses: ./
        with:
          webhook: ${{ secrets.FEISHU_URL }}
          title: "Hpc-Cloud代码推送通知"
          content: |
            AUTHOR: ${{ github.event.head_commit.author.name }}
            TIME: ${{ github.event.head_commit.timestamp }}
            COMMIT: ${{ github.event.head_commit.message }}
            {{ github.event.head_commit.url }}

  test_msg_type_post_by_using_bin_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send feishu message
        env:
          ACTIONS_FEISHU_TAG: 'v1.3.1'
          INPUT_WEBHOOK: "${{ secrets.FEISHU_URL }}"
          INPUT_TITLE: "Hpc-Cloud代码推送通知"
          INPUT_CONTENT: |
            AUTHOR: ${{ github.event.head_commit.author.name }}
            TIME: ${{ github.event.head_commit.timestamp }}
            COMMIT: ${{ github.event.head_commit.message }}
            {{ github.event.head_commit.url }}
        run: |
          wget -q https://github.com/xiachufang/actions-feishu/releases/download/${{ env.ACTIONS_FEISHU_TAG }}/linux-amd64-actions-feishu.tar.gz
          tar zxf linux-amd64-actions-feishu.tar.gz feishu
          ./feishu
